# Generated by Django 3.0.7 on 2020-11-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='month',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
