# Generated by Django 3.0.7 on 2020-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technical', 'Technical'), ('design', 'Design'), ('culture', 'Culture'), ('politics', 'Politics'), ('business', 'Business'), ('work', 'Work'), ('science', 'Science'), ('health', 'Health'), ('style', 'Style'), ('travel', 'Travel')], default='business', max_length=50),
        ),
    ]
